const quotes = [
  'The best way to get started is to quit talking and begin doing. — Walt Disney',
  'Don’t let yesterday take up too much of today. — Will Rogers',
  'It’s not whether you get knocked down, it’s whether you get up. — Vince Lombardi',
  'If you are working on something exciting, it will keep you motivated. — Steve Jobs',
  'Success is not in what you have, but who you are. — Bo Bennett',
  'The harder you work for something, the greater you’ll feel when you achieve it.',
  'Dream bigger. Do bigger.',
  'Don’t watch the clock; do what it does. Keep going. — Sam Levenson',
  'Great things never come from comfort zones.',
  'Push yourself, because no one else is going to do it for you.',
  'Sometimes later becomes never. Do it now.',
  'Success doesn’t just find you. You have to go out and get it.',
  'The key to success is to focus on goals, not obstacles.',
  'Dream it. Wish it. Do it.',
  'Hard work beats talent when talent doesn’t work hard. — Tim Notke',
  'Don’t stop when you’re tired. Stop when you’re done.',
  'Wake up with determination. Go to bed with satisfaction.',
  'Do something today that your future self will thank you for.',
  'Little things make big days.',
  'It’s going to be hard, but hard does not mean impossible.',
  'Don’t wait for opportunity. Create it.',
  'Sometimes we’re tested not to show our weaknesses, but to discover our strengths.',
  'The secret of getting ahead is getting started. — Mark Twain',
  'If you want to achieve greatness stop asking for permission.',
  'The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt',
  'It always seems impossible until it’s done. — Nelson Mandela',
  'Don’t wish it were easier. Wish you were better. — Jim Rohn',
  'Start where you are. Use what you have. Do what you can. — Arthur Ashe',
  'Your limitation—it’s only your imagination.',
  'Sometimes you win, sometimes you learn. — John Maxwell',
  'Discipline is the bridge between goals and accomplishment. — Jim Rohn',
  'If you get tired, learn to rest, not to quit. — Banksy',
  'What you get by achieving your goals is not as important as what you become by achieving them. — Zig Ziglar',
  'Doubt kills more dreams than failure ever will. — Suzy Kassem',
  'The future depends on what you do today. — Mahatma Gandhi',
  'Act as if what you do makes a difference. It does. — William James',
  'Quality means doing it right when no one is looking. — Henry Ford',
  'A goal without a plan is just a wish. — Antoine de Saint-Exupéry',
  'Work hard in silence, let your success be your noise. — Frank Ocean',
  'Believe you can and you’re halfway there. — Theodore Roosevelt',
  'Perseverance is not a long race; it is many short races one after another. — Walter Elliot',
  'Failure is simply the opportunity to begin again, this time more intelligently. — Henry Ford',
  'You don’t have to be great to start, but you have to start to be great. — Zig Ziglar',
  'You miss 100% of the shots you don’t take. — Wayne Gretzky',
  'Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau',
  'Innovation distinguishes between a leader and a follower. — Steve Jobs',
  'If something is important enough, even if the odds are against you, you should still do it. — Elon Musk',
  'The best revenge is massive success. — Frank Sinatra',
  'Don’t count the days, make the days count. — Muhammad Ali',
  'Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill',
  'In the middle of every difficulty lies opportunity. — Albert Einstein',
  'Do what you can, with what you have, where you are. — Theodore Roosevelt',
  'Action is the foundational key to all success. — Pablo Picasso',
  'The expert in anything was once a beginner.',
  'Failure is not the opposite of success; it’s part of success.',
  'Don’t be afraid to give up the good to go for the great. — John D. Rockefeller',
  'You don’t find willpower, you create it.',
  'If opportunity doesn’t knock, build a door. — Milton Berle',
  'Be so good they can’t ignore you. — Steve Martin',
  'If you’re going through hell, keep going. — Winston Churchill',
  'Make each day your masterpiece. — John Wooden',
  'Don’t limit your challenges—challenge your limits.',
  'You can’t use up creativity. The more you use, the more you have. — Maya Angelou',
  'Learn as if you were to live forever. — Mahatma Gandhi',
  'What we think, we become. — Buddha',
  'In order to be irreplaceable one must always be different. — Coco Chanel',
  'If you want to lift yourself up, lift up someone else. — Booker T. Washington',
  'Stay hungry, stay foolish. — Steve Jobs',
  'The biggest risk is not taking any risk. — Mark Zuckerberg',
  'Life is 10% what happens to us and 90% how we react to it. — Charles R. Swindoll',
  'Difficulties in life are intended to make us better, not bitter. — Dan Reeves',
  'The only way to do great work is to love what you do. — Steve Jobs',
  'Opportunities don’t happen, you create them. — Chris Grosser',
  'If you’re not willing to risk the usual, you’ll have to settle for the ordinary. — Jim Rohn',
  'Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill',
  'Be yourself; everyone else is already taken. — Oscar Wilde',
  'Your time is limited, don’t waste it living someone else’s life. — Steve Jobs',
  'You become what you believe. — Oprah Winfrey',
  'Whether you think you can or think you can’t, you’re right. — Henry Ford',
  'Courage doesn’t always roar; sometimes it’s the quiet voice saying, ‘I will try again tomorrow.’ — Mary Anne Radmacher',
  'Don’t be pushed by your problems; be led by your dreams. — Ralph Waldo Emerson',
  'Strive not to be a success, but rather to be of value. — Albert Einstein',
  'What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson',
  'The best preparation for tomorrow is doing your best today. — H. Jackson Brown Jr.',
  'The man who moves a mountain begins by carrying away small stones. — Confucius',
  'Don’t compare your beginning to someone else’s middle.',
  'Doubt whom you will, but never yourself. — Christian Nestell Bovee',
  'Success doesn’t come from what you do occasionally, it comes from what you do consistently.',
  'The way to get started is to quit talking and begin doing. — Walt Disney',
  'Be stronger than your excuses.',
  'Consistency is what transforms average into excellence.',
  'Don’t wait for the perfect moment, take the moment and make it perfect.',
  'Difficult roads often lead to beautiful destinations.',
  'You don’t have to see the whole staircase, just take the first step. — Martin Luther King Jr.',
  'The only person you should try to be better than is the person you were yesterday.',
  'Success is not about being the best. It’s about always getting better.',
  'You can’t change the direction of the wind, but you can adjust your sails. — Jimmy Dean',
  'If you want something you’ve never had, you must be willing to do something you’ve never done.',
];

const qoute = document.querySelector('#quote');

const button = document.querySelector('button');
button.addEventListener('click', () => {
  qoute.innerHTML = quotes[Math.floor(Math.random() * 100)];
});
