export const cricketQuestions = [
  {
    id: 1,
    question: "Who is known as the 'God of Cricket'?",
    options: ['Sachin Tendulkar', 'Ricky Ponting', 'Brian Lara', 'Virat Kohli'],
    answer: 1,
  },
  {
    id: 2,
    question: 'Which country won the first ICC Cricket World Cup in 1975?',
    options: ['Australia', 'West Indies', 'India', 'England'],
    answer: 2,
  },
  {
    id: 3,
    question: 'How many players are there in a standard cricket team?',
    options: ['9', '10', '11', '12'],
    answer: 3,
  },
  {
    id: 4,
    question: 'Who was the captain of India during the 2011 World Cup win?',
    options: ['MS Dhoni', 'Sourav Ganguly', 'Virat Kohli', 'Rahul Dravid'],
    answer: 1,
  },
  {
    id: 5,
    question: 'What is the length of a cricket pitch?',
    options: ['20 yards', '22 yards', '24 yards', '25 yards'],
    answer: 2,
  },
  {
    id: 6,
    question: 'Which bowler has taken the most wickets in Test cricket?',
    options: [
      'Shane Warne',
      'Muttiah Muralitharan',
      'James Anderson',
      'Anil Kumble',
    ],
    answer: 2,
  },
  {
    id: 7,
    question: 'Which country is called the birthplace of cricket?',
    options: ['India', 'Australia', 'England', 'South Africa'],
    answer: 3,
  },
  {
    id: 8,
    question: 'Who scored the first double century in ODI cricket?',
    options: [
      'Rohit Sharma',
      'Sachin Tendulkar',
      'Virender Sehwag',
      'Chris Gayle',
    ],
    answer: 2,
  },
  {
    id: 9,
    question: "Who is known as the 'Universe Boss'?",
    options: [
      'AB de Villiers',
      'Chris Gayle',
      'Kieron Pollard',
      'Andre Russell',
    ],
    answer: 2,
  },
  {
    id: 10,
    question: "Which Indian cricketer is nicknamed 'The Wall'?",
    options: ['Rahul Dravid', 'Sourav Ganguly', 'VVS Laxman', 'MS Dhoni'],
    answer: 1,
  },
  {
    id: 11,
    question: 'Who was the first captain of the Indian cricket team?',
    options: ['Lala Amarnath', 'CK Nayudu', 'Vijay Hazare', 'Polly Umrigar'],
    answer: 2,
  },
  {
    id: 12,
    question: 'Which Indian player scored 10,000 runs in ODIs first?',
    options: [
      'Rahul Dravid',
      'Sourav Ganguly',
      'Sachin Tendulkar',
      'Virat Kohli',
    ],
    answer: 3,
  },
  {
    id: 13,
    question: "Which bowler is famous for the 'Doosra' delivery?",
    options: [
      'Harbhajan Singh',
      'Saqlain Mushtaq',
      'Muttiah Muralitharan',
      'Shahid Afridi',
    ],
    answer: 2,
  },
  {
    id: 14,
    question: 'In which year did India win its first T20 World Cup?',
    options: ['2007', '2009', '2011', '2013'],
    answer: 1,
  },
  {
    id: 15,
    question: 'Who holds the record for the fastest century in ODI cricket?',
    options: [
      'AB de Villiers',
      'Shahid Afridi',
      'Corey Anderson',
      'Chris Gayle',
    ],
    answer: 1,
  },
  {
    id: 16,
    question: 'Which country hosted the 2019 Cricket World Cup?',
    options: ['India', 'Australia', 'England', 'South Africa'],
    answer: 3,
  },
  {
    id: 17,
    question: 'Who bowled the first ball in IPL history?',
    options: ['Zaheer Khan', 'Glenn McGrath', 'Praveen Kumar', 'Shoaib Akhtar'],
    answer: 3,
  },
  {
    id: 18,
    question: 'Which team won the first IPL trophy in 2008?',
    options: [
      'Chennai Super Kings',
      'Rajasthan Royals',
      'Mumbai Indians',
      'Kolkata Knight Riders',
    ],
    answer: 2,
  },
  {
    id: 19,
    question: 'Who has scored the most centuries in international cricket?',
    options: [
      'Virat Kohli',
      'Ricky Ponting',
      'Sachin Tendulkar',
      'Jacques Kallis',
    ],
    answer: 3,
  },
  {
    id: 20,
    question: "Which player is known as 'Captain Cool'?",
    options: ['Rohit Sharma', 'MS Dhoni', 'Kane Williamson', 'Steve Smith'],
    answer: 2,
  },
  {
    id: 21,
    question:
      'Who holds the record for the highest individual score in ODI cricket?',
    options: ['Rohit Sharma', 'Martin Guptill', 'Chris Gayle', 'Fakhar Zaman'],
    answer: 1,
  },
  {
    id: 22,
    question: "Which cricketer is known as 'Mr. 360'?",
    options: ['AB de Villiers', 'Glenn Maxwell', 'Jos Buttler', 'David Warner'],
    answer: 1,
  },
  {
    id: 23,
    question: 'Which country has won the most Cricket World Cups?',
    options: ['India', 'West Indies', 'Australia', 'England'],
    answer: 3,
  },
  {
    id: 24,
    question: 'Which Indian city has the Eden Gardens stadium?',
    options: ['Mumbai', 'Delhi', 'Kolkata', 'Chennai'],
    answer: 3,
  },
  {
    id: 25,
    question: 'Who took the first hat-trick in a World Cup match?',
    options: ['Chetan Sharma', 'Lasith Malinga', 'Brett Lee', 'Wasim Akram'],
    answer: 1,
  },
  {
    id: 26,
    question: 'Which cricketer has scored three double centuries in ODIs?',
    options: [
      'Rohit Sharma',
      'Virender Sehwag',
      'Chris Gayle',
      'Sachin Tendulkar',
    ],
    answer: 1,
  },
  {
    id: 27,
    question: 'Who hit six sixes in an over in T20 World Cup 2007?',
    options: ['Yuvraj Singh', 'Chris Gayle', 'Shahid Afridi', 'MS Dhoni'],
    answer: 1,
  },
  {
    id: 28,
    question: 'Which country hosted the first ever Day-Night Test match?',
    options: ['Australia', 'India', 'England', 'New Zealand'],
    answer: 1,
  },
  {
    id: 29,
    question: 'Which cricket stadium is the largest in the world?',
    options: ['Eden Gardens', 'MCG', 'Narendra Modi Stadium', 'Lords'],
    answer: 3,
  },
  {
    id: 30,
    question: 'Who is the fastest batsman to reach 8000 ODI runs?',
    options: ['AB de Villiers', 'Virat Kohli', 'Rohit Sharma', 'Hashim Amla'],
    answer: 2,
  },
];
